# Generated by Django 3.2 on 2021-06-16 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Endereço de Email')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now=True)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('rua', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=5, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('portas', models.IntegerField()),
                ('assentos', models.IntegerField()),
                ('transmissao', models.IntegerField()),
                ('idade_minima', models.IntegerField()),
                ('preco_locacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagem_carro', stdimage.models.StdImageField(blank=True, null=True, upload_to=service.models.get_file_path, verbose_name='Imagem_carro')),
            ],
            options={
                'db_table': 'carro',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=16)),
                ('mes_validade', models.IntegerField()),
                ('ano_validade', models.IntegerField()),
                ('codigo_seguranca', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('tipo_cartao', models.IntegerField()),
                ('nome_cartao', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metodo_pagamento',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('devolucao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('telefone', models.CharField(max_length=13)),
                ('cnh', models.CharField(max_length=11)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.carro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('endereco_devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_devolucao', to='service.endereco')),
                ('endereco_retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_retirada', to='service.endereco')),
                ('metodo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.metodopagamento')),
            ],
            options={
                'db_table': 'locacao',
            },
        ),
    ]
